import env from '@common/config/env'

export const JWT_SECRET = env.JWT_SECRET
export const JWT_REFRESH_SECRET = env.JWT_REFRESH_SECRET

export const JWT_ACCESS_EXPIRES_IN_SECONDS = env.JWT_ACCESS_EXPIRES_IN
export const JWT_REFRESH_EXPIRES_IN_SECONDS = env.JWT_REFRESH_EXPIRES_IN
export const MAX_SESSION_LIFETIME_IN_SECONDS = env.MAX_SESSION_LIFETIME_IN

export const JWT_REFRESH_EXPIRES_IN_MS = JWT_REFRESH_EXPIRES_IN_SECONDS * 1000
export const MAX_SESSION_LIFETIME_IN_MS = MAX_SESSION_LIFETIME_IN_SECONDS * 1000
